language: dart
dart: dev
sudo: false
dart_task:
- test: --platform vm
script:
  - pub run test
  - pub global activate dart_coveralls

after_success:
  - dart_coveralls report --package-root=lib --token=lrho1ih0tXTPQZFUDwZ8IRdJ1KDjSRPz0 test/dashboard_api_test.dart